const ACTIONS = {
    SET_CURRENT: 'show/SET_CURRENT',
    SET_FORECAST: 'show/SET_FORECAST',
    SET_CURRENT_LOADING: 'show/SET_CURRENT_LOADING',
    SET_FORECAST_LOADING: 'show/SET_FORECAST_LOADING'
};

export default ACTIONS;